/*
 * WooCommerce REST API
 * The REST API is a powerful part of WooCommerce which lets you read and write various parts of WooCommerce data such as orders, products, coupons, customers, and shipping zones.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.woocommerce.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import pl.wtx.woocommerce.api.client.model.MetaData;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.woocommerce.api.client.invoker.JSON;

/**
 * Coupon
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Coupon {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nullable
  private String code;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  @javax.annotation.Nullable
  private String amount;

  public static final String SERIALIZED_NAME_DATE_CREATED = "date_created";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED)
  @javax.annotation.Nullable
  private OffsetDateTime dateCreated;

  public static final String SERIALIZED_NAME_DATE_CREATED_GMT = "date_created_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED_GMT)
  @javax.annotation.Nullable
  private OffsetDateTime dateCreatedGmt;

  public static final String SERIALIZED_NAME_DATE_MODIFIED = "date_modified";
  @SerializedName(SERIALIZED_NAME_DATE_MODIFIED)
  @javax.annotation.Nullable
  private OffsetDateTime dateModified;

  public static final String SERIALIZED_NAME_DATE_MODIFIED_GMT = "date_modified_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_MODIFIED_GMT)
  @javax.annotation.Nullable
  private OffsetDateTime dateModifiedGmt;

  /**
   * Determines the type of discount that will be applied.
   */
  @JsonAdapter(DiscountTypeEnum.Adapter.class)
  public enum DiscountTypeEnum {
    PERCENT("percent"),
    
    FIXED_CART("fixed_cart"),
    
    FIXED_PRODUCT("fixed_product");

    private String value;

    DiscountTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DiscountTypeEnum fromValue(String value) {
      for (DiscountTypeEnum b : DiscountTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DiscountTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DiscountTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DiscountTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DiscountTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DiscountTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DISCOUNT_TYPE = "discount_type";
  @SerializedName(SERIALIZED_NAME_DISCOUNT_TYPE)
  @javax.annotation.Nullable
  private DiscountTypeEnum discountType = DiscountTypeEnum.FIXED_CART;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_DATE_EXPIRES = "date_expires";
  @SerializedName(SERIALIZED_NAME_DATE_EXPIRES)
  @javax.annotation.Nullable
  private OffsetDateTime dateExpires;

  public static final String SERIALIZED_NAME_DATE_EXPIRES_GMT = "date_expires_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_EXPIRES_GMT)
  @javax.annotation.Nullable
  private OffsetDateTime dateExpiresGmt;

  public static final String SERIALIZED_NAME_USAGE_COUNT = "usage_count";
  @SerializedName(SERIALIZED_NAME_USAGE_COUNT)
  @javax.annotation.Nullable
  private Integer usageCount;

  public static final String SERIALIZED_NAME_INDIVIDUAL_USE = "individual_use";
  @SerializedName(SERIALIZED_NAME_INDIVIDUAL_USE)
  @javax.annotation.Nullable
  private Boolean individualUse = false;

  public static final String SERIALIZED_NAME_PRODUCT_IDS = "product_ids";
  @SerializedName(SERIALIZED_NAME_PRODUCT_IDS)
  @javax.annotation.Nullable
  private List<Integer> productIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXCLUDED_PRODUCT_IDS = "excluded_product_ids";
  @SerializedName(SERIALIZED_NAME_EXCLUDED_PRODUCT_IDS)
  @javax.annotation.Nullable
  private List<Integer> excludedProductIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_USAGE_LIMIT = "usage_limit";
  @SerializedName(SERIALIZED_NAME_USAGE_LIMIT)
  @javax.annotation.Nullable
  private Integer usageLimit;

  public static final String SERIALIZED_NAME_USAGE_LIMIT_PER_USER = "usage_limit_per_user";
  @SerializedName(SERIALIZED_NAME_USAGE_LIMIT_PER_USER)
  @javax.annotation.Nullable
  private Integer usageLimitPerUser;

  public static final String SERIALIZED_NAME_LIMIT_USAGE_TO_X_ITEMS = "limit_usage_to_x_items";
  @SerializedName(SERIALIZED_NAME_LIMIT_USAGE_TO_X_ITEMS)
  @javax.annotation.Nullable
  private Integer limitUsageToXItems;

  public static final String SERIALIZED_NAME_FREE_SHIPPING = "free_shipping";
  @SerializedName(SERIALIZED_NAME_FREE_SHIPPING)
  @javax.annotation.Nullable
  private Boolean freeShipping = false;

  public static final String SERIALIZED_NAME_PRODUCT_CATEGORIES = "product_categories";
  @SerializedName(SERIALIZED_NAME_PRODUCT_CATEGORIES)
  @javax.annotation.Nullable
  private List<Integer> productCategories = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXCLUDED_PRODUCT_CATEGORIES = "excluded_product_categories";
  @SerializedName(SERIALIZED_NAME_EXCLUDED_PRODUCT_CATEGORIES)
  @javax.annotation.Nullable
  private List<Integer> excludedProductCategories = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXCLUDE_SALE_ITEMS = "exclude_sale_items";
  @SerializedName(SERIALIZED_NAME_EXCLUDE_SALE_ITEMS)
  @javax.annotation.Nullable
  private Boolean excludeSaleItems = false;

  public static final String SERIALIZED_NAME_MINIMUM_AMOUNT = "minimum_amount";
  @SerializedName(SERIALIZED_NAME_MINIMUM_AMOUNT)
  @javax.annotation.Nullable
  private String minimumAmount;

  public static final String SERIALIZED_NAME_MAXIMUM_AMOUNT = "maximum_amount";
  @SerializedName(SERIALIZED_NAME_MAXIMUM_AMOUNT)
  @javax.annotation.Nullable
  private String maximumAmount;

  public static final String SERIALIZED_NAME_EMAIL_RESTRICTIONS = "email_restrictions";
  @SerializedName(SERIALIZED_NAME_EMAIL_RESTRICTIONS)
  @javax.annotation.Nullable
  private List<String> emailRestrictions = new ArrayList<>();

  public static final String SERIALIZED_NAME_META_DATA = "meta_data";
  @SerializedName(SERIALIZED_NAME_META_DATA)
  @javax.annotation.Nullable
  private List<MetaData> metaData = new ArrayList<>();

  public Coupon() {
  }

  public Coupon id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier for the resource. read-only
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public Coupon code(@javax.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * Coupon code. mandatory
   * @return code
   */
  @javax.annotation.Nullable
  public String getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }


  public Coupon amount(@javax.annotation.Nullable String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * The amount of discount. Should always be numeric, even if setting a percentage.
   * @return amount
   */
  @javax.annotation.Nullable
  public String getAmount() {
    return amount;
  }

  public void setAmount(@javax.annotation.Nullable String amount) {
    this.amount = amount;
  }


  public Coupon dateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * The date the coupon was created, in the site&#39;s timezone. read-only
   * @return dateCreated
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(@javax.annotation.Nullable OffsetDateTime dateCreated) {
    this.dateCreated = dateCreated;
  }


  public Coupon dateCreatedGmt(@javax.annotation.Nullable OffsetDateTime dateCreatedGmt) {
    this.dateCreatedGmt = dateCreatedGmt;
    return this;
  }

  /**
   * The date the coupon was created, as GMT. read-only
   * @return dateCreatedGmt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateCreatedGmt() {
    return dateCreatedGmt;
  }

  public void setDateCreatedGmt(@javax.annotation.Nullable OffsetDateTime dateCreatedGmt) {
    this.dateCreatedGmt = dateCreatedGmt;
  }


  public Coupon dateModified(@javax.annotation.Nullable OffsetDateTime dateModified) {
    this.dateModified = dateModified;
    return this;
  }

  /**
   * The date the coupon was last modified, in the site&#39;s timezone. read-only
   * @return dateModified
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateModified() {
    return dateModified;
  }

  public void setDateModified(@javax.annotation.Nullable OffsetDateTime dateModified) {
    this.dateModified = dateModified;
  }


  public Coupon dateModifiedGmt(@javax.annotation.Nullable OffsetDateTime dateModifiedGmt) {
    this.dateModifiedGmt = dateModifiedGmt;
    return this;
  }

  /**
   * The date the coupon was last modified, as GMT. read-only
   * @return dateModifiedGmt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateModifiedGmt() {
    return dateModifiedGmt;
  }

  public void setDateModifiedGmt(@javax.annotation.Nullable OffsetDateTime dateModifiedGmt) {
    this.dateModifiedGmt = dateModifiedGmt;
  }


  public Coupon discountType(@javax.annotation.Nullable DiscountTypeEnum discountType) {
    this.discountType = discountType;
    return this;
  }

  /**
   * Determines the type of discount that will be applied.
   * @return discountType
   */
  @javax.annotation.Nullable
  public DiscountTypeEnum getDiscountType() {
    return discountType;
  }

  public void setDiscountType(@javax.annotation.Nullable DiscountTypeEnum discountType) {
    this.discountType = discountType;
  }


  public Coupon description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Coupon description.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public Coupon dateExpires(@javax.annotation.Nullable OffsetDateTime dateExpires) {
    this.dateExpires = dateExpires;
    return this;
  }

  /**
   * The date the coupon expires, in the site&#39;s timezone.
   * @return dateExpires
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateExpires() {
    return dateExpires;
  }

  public void setDateExpires(@javax.annotation.Nullable OffsetDateTime dateExpires) {
    this.dateExpires = dateExpires;
  }


  public Coupon dateExpiresGmt(@javax.annotation.Nullable OffsetDateTime dateExpiresGmt) {
    this.dateExpiresGmt = dateExpiresGmt;
    return this;
  }

  /**
   * The date the coupon expires, as GMT.
   * @return dateExpiresGmt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDateExpiresGmt() {
    return dateExpiresGmt;
  }

  public void setDateExpiresGmt(@javax.annotation.Nullable OffsetDateTime dateExpiresGmt) {
    this.dateExpiresGmt = dateExpiresGmt;
  }


  public Coupon usageCount(@javax.annotation.Nullable Integer usageCount) {
    this.usageCount = usageCount;
    return this;
  }

  /**
   * Number of times the coupon has been used already. read-only
   * @return usageCount
   */
  @javax.annotation.Nullable
  public Integer getUsageCount() {
    return usageCount;
  }

  public void setUsageCount(@javax.annotation.Nullable Integer usageCount) {
    this.usageCount = usageCount;
  }


  public Coupon individualUse(@javax.annotation.Nullable Boolean individualUse) {
    this.individualUse = individualUse;
    return this;
  }

  /**
   * If true, the coupon can only be used individually. Other applied coupons will be removed from the cart.
   * @return individualUse
   */
  @javax.annotation.Nullable
  public Boolean getIndividualUse() {
    return individualUse;
  }

  public void setIndividualUse(@javax.annotation.Nullable Boolean individualUse) {
    this.individualUse = individualUse;
  }


  public Coupon productIds(@javax.annotation.Nullable List<Integer> productIds) {
    this.productIds = productIds;
    return this;
  }

  public Coupon addProductIdsItem(Integer productIdsItem) {
    if (this.productIds == null) {
      this.productIds = new ArrayList<>();
    }
    this.productIds.add(productIdsItem);
    return this;
  }

  /**
   * List of product IDs the coupon can be used on.
   * @return productIds
   */
  @javax.annotation.Nullable
  public List<Integer> getProductIds() {
    return productIds;
  }

  public void setProductIds(@javax.annotation.Nullable List<Integer> productIds) {
    this.productIds = productIds;
  }


  public Coupon excludedProductIds(@javax.annotation.Nullable List<Integer> excludedProductIds) {
    this.excludedProductIds = excludedProductIds;
    return this;
  }

  public Coupon addExcludedProductIdsItem(Integer excludedProductIdsItem) {
    if (this.excludedProductIds == null) {
      this.excludedProductIds = new ArrayList<>();
    }
    this.excludedProductIds.add(excludedProductIdsItem);
    return this;
  }

  /**
   * List of product IDs the coupon cannot be used on.
   * @return excludedProductIds
   */
  @javax.annotation.Nullable
  public List<Integer> getExcludedProductIds() {
    return excludedProductIds;
  }

  public void setExcludedProductIds(@javax.annotation.Nullable List<Integer> excludedProductIds) {
    this.excludedProductIds = excludedProductIds;
  }


  public Coupon usageLimit(@javax.annotation.Nullable Integer usageLimit) {
    this.usageLimit = usageLimit;
    return this;
  }

  /**
   * How many times the coupon can be used in total.
   * @return usageLimit
   */
  @javax.annotation.Nullable
  public Integer getUsageLimit() {
    return usageLimit;
  }

  public void setUsageLimit(@javax.annotation.Nullable Integer usageLimit) {
    this.usageLimit = usageLimit;
  }


  public Coupon usageLimitPerUser(@javax.annotation.Nullable Integer usageLimitPerUser) {
    this.usageLimitPerUser = usageLimitPerUser;
    return this;
  }

  /**
   * How many times the coupon can be used per customer.
   * @return usageLimitPerUser
   */
  @javax.annotation.Nullable
  public Integer getUsageLimitPerUser() {
    return usageLimitPerUser;
  }

  public void setUsageLimitPerUser(@javax.annotation.Nullable Integer usageLimitPerUser) {
    this.usageLimitPerUser = usageLimitPerUser;
  }


  public Coupon limitUsageToXItems(@javax.annotation.Nullable Integer limitUsageToXItems) {
    this.limitUsageToXItems = limitUsageToXItems;
    return this;
  }

  /**
   * Max number of items in the cart the coupon can be applied to.
   * @return limitUsageToXItems
   */
  @javax.annotation.Nullable
  public Integer getLimitUsageToXItems() {
    return limitUsageToXItems;
  }

  public void setLimitUsageToXItems(@javax.annotation.Nullable Integer limitUsageToXItems) {
    this.limitUsageToXItems = limitUsageToXItems;
  }


  public Coupon freeShipping(@javax.annotation.Nullable Boolean freeShipping) {
    this.freeShipping = freeShipping;
    return this;
  }

  /**
   * If true and if the free shipping method requires a coupon, this coupon will enable free shipping.
   * @return freeShipping
   */
  @javax.annotation.Nullable
  public Boolean getFreeShipping() {
    return freeShipping;
  }

  public void setFreeShipping(@javax.annotation.Nullable Boolean freeShipping) {
    this.freeShipping = freeShipping;
  }


  public Coupon productCategories(@javax.annotation.Nullable List<Integer> productCategories) {
    this.productCategories = productCategories;
    return this;
  }

  public Coupon addProductCategoriesItem(Integer productCategoriesItem) {
    if (this.productCategories == null) {
      this.productCategories = new ArrayList<>();
    }
    this.productCategories.add(productCategoriesItem);
    return this;
  }

  /**
   * List of category IDs the coupon applies to.
   * @return productCategories
   */
  @javax.annotation.Nullable
  public List<Integer> getProductCategories() {
    return productCategories;
  }

  public void setProductCategories(@javax.annotation.Nullable List<Integer> productCategories) {
    this.productCategories = productCategories;
  }


  public Coupon excludedProductCategories(@javax.annotation.Nullable List<Integer> excludedProductCategories) {
    this.excludedProductCategories = excludedProductCategories;
    return this;
  }

  public Coupon addExcludedProductCategoriesItem(Integer excludedProductCategoriesItem) {
    if (this.excludedProductCategories == null) {
      this.excludedProductCategories = new ArrayList<>();
    }
    this.excludedProductCategories.add(excludedProductCategoriesItem);
    return this;
  }

  /**
   * List of category IDs the coupon does not apply to.
   * @return excludedProductCategories
   */
  @javax.annotation.Nullable
  public List<Integer> getExcludedProductCategories() {
    return excludedProductCategories;
  }

  public void setExcludedProductCategories(@javax.annotation.Nullable List<Integer> excludedProductCategories) {
    this.excludedProductCategories = excludedProductCategories;
  }


  public Coupon excludeSaleItems(@javax.annotation.Nullable Boolean excludeSaleItems) {
    this.excludeSaleItems = excludeSaleItems;
    return this;
  }

  /**
   * If true, this coupon will not be applied to items that have sale prices.
   * @return excludeSaleItems
   */
  @javax.annotation.Nullable
  public Boolean getExcludeSaleItems() {
    return excludeSaleItems;
  }

  public void setExcludeSaleItems(@javax.annotation.Nullable Boolean excludeSaleItems) {
    this.excludeSaleItems = excludeSaleItems;
  }


  public Coupon minimumAmount(@javax.annotation.Nullable String minimumAmount) {
    this.minimumAmount = minimumAmount;
    return this;
  }

  /**
   * Minimum order amount that needs to be in the cart before coupon applies.
   * @return minimumAmount
   */
  @javax.annotation.Nullable
  public String getMinimumAmount() {
    return minimumAmount;
  }

  public void setMinimumAmount(@javax.annotation.Nullable String minimumAmount) {
    this.minimumAmount = minimumAmount;
  }


  public Coupon maximumAmount(@javax.annotation.Nullable String maximumAmount) {
    this.maximumAmount = maximumAmount;
    return this;
  }

  /**
   * Maximum order amount allowed when using the coupon.
   * @return maximumAmount
   */
  @javax.annotation.Nullable
  public String getMaximumAmount() {
    return maximumAmount;
  }

  public void setMaximumAmount(@javax.annotation.Nullable String maximumAmount) {
    this.maximumAmount = maximumAmount;
  }


  public Coupon emailRestrictions(@javax.annotation.Nullable List<String> emailRestrictions) {
    this.emailRestrictions = emailRestrictions;
    return this;
  }

  public Coupon addEmailRestrictionsItem(String emailRestrictionsItem) {
    if (this.emailRestrictions == null) {
      this.emailRestrictions = new ArrayList<>();
    }
    this.emailRestrictions.add(emailRestrictionsItem);
    return this;
  }

  /**
   * List of email addresses that can use this coupon.
   * @return emailRestrictions
   */
  @javax.annotation.Nullable
  public List<String> getEmailRestrictions() {
    return emailRestrictions;
  }

  public void setEmailRestrictions(@javax.annotation.Nullable List<String> emailRestrictions) {
    this.emailRestrictions = emailRestrictions;
  }


  public Coupon metaData(@javax.annotation.Nullable List<MetaData> metaData) {
    this.metaData = metaData;
    return this;
  }

  public Coupon addMetaDataItem(MetaData metaDataItem) {
    if (this.metaData == null) {
      this.metaData = new ArrayList<>();
    }
    this.metaData.add(metaDataItem);
    return this;
  }

  /**
   * Meta data.
   * @return metaData
   */
  @javax.annotation.Nullable
  public List<MetaData> getMetaData() {
    return metaData;
  }

  public void setMetaData(@javax.annotation.Nullable List<MetaData> metaData) {
    this.metaData = metaData;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Coupon coupon = (Coupon) o;
    return Objects.equals(this.id, coupon.id) &&
        Objects.equals(this.code, coupon.code) &&
        Objects.equals(this.amount, coupon.amount) &&
        Objects.equals(this.dateCreated, coupon.dateCreated) &&
        Objects.equals(this.dateCreatedGmt, coupon.dateCreatedGmt) &&
        Objects.equals(this.dateModified, coupon.dateModified) &&
        Objects.equals(this.dateModifiedGmt, coupon.dateModifiedGmt) &&
        Objects.equals(this.discountType, coupon.discountType) &&
        Objects.equals(this.description, coupon.description) &&
        Objects.equals(this.dateExpires, coupon.dateExpires) &&
        Objects.equals(this.dateExpiresGmt, coupon.dateExpiresGmt) &&
        Objects.equals(this.usageCount, coupon.usageCount) &&
        Objects.equals(this.individualUse, coupon.individualUse) &&
        Objects.equals(this.productIds, coupon.productIds) &&
        Objects.equals(this.excludedProductIds, coupon.excludedProductIds) &&
        Objects.equals(this.usageLimit, coupon.usageLimit) &&
        Objects.equals(this.usageLimitPerUser, coupon.usageLimitPerUser) &&
        Objects.equals(this.limitUsageToXItems, coupon.limitUsageToXItems) &&
        Objects.equals(this.freeShipping, coupon.freeShipping) &&
        Objects.equals(this.productCategories, coupon.productCategories) &&
        Objects.equals(this.excludedProductCategories, coupon.excludedProductCategories) &&
        Objects.equals(this.excludeSaleItems, coupon.excludeSaleItems) &&
        Objects.equals(this.minimumAmount, coupon.minimumAmount) &&
        Objects.equals(this.maximumAmount, coupon.maximumAmount) &&
        Objects.equals(this.emailRestrictions, coupon.emailRestrictions) &&
        Objects.equals(this.metaData, coupon.metaData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, code, amount, dateCreated, dateCreatedGmt, dateModified, dateModifiedGmt, discountType, description, dateExpires, dateExpiresGmt, usageCount, individualUse, productIds, excludedProductIds, usageLimit, usageLimitPerUser, limitUsageToXItems, freeShipping, productCategories, excludedProductCategories, excludeSaleItems, minimumAmount, maximumAmount, emailRestrictions, metaData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Coupon {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateCreatedGmt: ").append(toIndentedString(dateCreatedGmt)).append("\n");
    sb.append("    dateModified: ").append(toIndentedString(dateModified)).append("\n");
    sb.append("    dateModifiedGmt: ").append(toIndentedString(dateModifiedGmt)).append("\n");
    sb.append("    discountType: ").append(toIndentedString(discountType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    dateExpires: ").append(toIndentedString(dateExpires)).append("\n");
    sb.append("    dateExpiresGmt: ").append(toIndentedString(dateExpiresGmt)).append("\n");
    sb.append("    usageCount: ").append(toIndentedString(usageCount)).append("\n");
    sb.append("    individualUse: ").append(toIndentedString(individualUse)).append("\n");
    sb.append("    productIds: ").append(toIndentedString(productIds)).append("\n");
    sb.append("    excludedProductIds: ").append(toIndentedString(excludedProductIds)).append("\n");
    sb.append("    usageLimit: ").append(toIndentedString(usageLimit)).append("\n");
    sb.append("    usageLimitPerUser: ").append(toIndentedString(usageLimitPerUser)).append("\n");
    sb.append("    limitUsageToXItems: ").append(toIndentedString(limitUsageToXItems)).append("\n");
    sb.append("    freeShipping: ").append(toIndentedString(freeShipping)).append("\n");
    sb.append("    productCategories: ").append(toIndentedString(productCategories)).append("\n");
    sb.append("    excludedProductCategories: ").append(toIndentedString(excludedProductCategories)).append("\n");
    sb.append("    excludeSaleItems: ").append(toIndentedString(excludeSaleItems)).append("\n");
    sb.append("    minimumAmount: ").append(toIndentedString(minimumAmount)).append("\n");
    sb.append("    maximumAmount: ").append(toIndentedString(maximumAmount)).append("\n");
    sb.append("    emailRestrictions: ").append(toIndentedString(emailRestrictions)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("code");
    openapiFields.add("amount");
    openapiFields.add("date_created");
    openapiFields.add("date_created_gmt");
    openapiFields.add("date_modified");
    openapiFields.add("date_modified_gmt");
    openapiFields.add("discount_type");
    openapiFields.add("description");
    openapiFields.add("date_expires");
    openapiFields.add("date_expires_gmt");
    openapiFields.add("usage_count");
    openapiFields.add("individual_use");
    openapiFields.add("product_ids");
    openapiFields.add("excluded_product_ids");
    openapiFields.add("usage_limit");
    openapiFields.add("usage_limit_per_user");
    openapiFields.add("limit_usage_to_x_items");
    openapiFields.add("free_shipping");
    openapiFields.add("product_categories");
    openapiFields.add("excluded_product_categories");
    openapiFields.add("exclude_sale_items");
    openapiFields.add("minimum_amount");
    openapiFields.add("maximum_amount");
    openapiFields.add("email_restrictions");
    openapiFields.add("meta_data");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Coupon
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Coupon.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Coupon is not found in the empty JSON string", Coupon.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Coupon.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Coupon` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("code") != null && !jsonObj.get("code").isJsonNull()) && !jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      if ((jsonObj.get("amount") != null && !jsonObj.get("amount").isJsonNull()) && !jsonObj.get("amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount").toString()));
      }
      if ((jsonObj.get("discount_type") != null && !jsonObj.get("discount_type").isJsonNull()) && !jsonObj.get("discount_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `discount_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("discount_type").toString()));
      }
      // validate the optional field `discount_type`
      if (jsonObj.get("discount_type") != null && !jsonObj.get("discount_type").isJsonNull()) {
        DiscountTypeEnum.validateJsonElement(jsonObj.get("discount_type"));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("product_ids") != null && !jsonObj.get("product_ids").isJsonNull() && !jsonObj.get("product_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `product_ids` to be an array in the JSON string but got `%s`", jsonObj.get("product_ids").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("excluded_product_ids") != null && !jsonObj.get("excluded_product_ids").isJsonNull() && !jsonObj.get("excluded_product_ids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `excluded_product_ids` to be an array in the JSON string but got `%s`", jsonObj.get("excluded_product_ids").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("product_categories") != null && !jsonObj.get("product_categories").isJsonNull() && !jsonObj.get("product_categories").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `product_categories` to be an array in the JSON string but got `%s`", jsonObj.get("product_categories").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("excluded_product_categories") != null && !jsonObj.get("excluded_product_categories").isJsonNull() && !jsonObj.get("excluded_product_categories").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `excluded_product_categories` to be an array in the JSON string but got `%s`", jsonObj.get("excluded_product_categories").toString()));
      }
      if ((jsonObj.get("minimum_amount") != null && !jsonObj.get("minimum_amount").isJsonNull()) && !jsonObj.get("minimum_amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `minimum_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("minimum_amount").toString()));
      }
      if ((jsonObj.get("maximum_amount") != null && !jsonObj.get("maximum_amount").isJsonNull()) && !jsonObj.get("maximum_amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `maximum_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("maximum_amount").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("email_restrictions") != null && !jsonObj.get("email_restrictions").isJsonNull() && !jsonObj.get("email_restrictions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `email_restrictions` to be an array in the JSON string but got `%s`", jsonObj.get("email_restrictions").toString()));
      }
      if (jsonObj.get("meta_data") != null && !jsonObj.get("meta_data").isJsonNull()) {
        JsonArray jsonArraymetaData = jsonObj.getAsJsonArray("meta_data");
        if (jsonArraymetaData != null) {
          // ensure the json data is an array
          if (!jsonObj.get("meta_data").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `meta_data` to be an array in the JSON string but got `%s`", jsonObj.get("meta_data").toString()));
          }

          // validate the optional field `meta_data` (array)
          for (int i = 0; i < jsonArraymetaData.size(); i++) {
            MetaData.validateJsonElement(jsonArraymetaData.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Coupon.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Coupon' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Coupon> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Coupon.class));

       return (TypeAdapter<T>) new TypeAdapter<Coupon>() {
           @Override
           public void write(JsonWriter out, Coupon value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Coupon read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Coupon given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Coupon
   * @throws IOException if the JSON string is invalid with respect to Coupon
   */
  public static Coupon fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Coupon.class);
  }

  /**
   * Convert an instance of Coupon to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

