/*
 * WooCommerce REST API
 * The REST API is a powerful part of WooCommerce which lets you read and write various parts of WooCommerce data such as orders, products, coupons, customers, and shipping zones.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.woocommerce.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.woocommerce.api.client.invoker.JSON;

/**
 * OrderRefundLineItemsInnerTaxesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class OrderRefundLineItemsInnerTaxesInner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  @javax.annotation.Nullable
  private String total;

  public static final String SERIALIZED_NAME_SUBTOTAL = "subtotal";
  @SerializedName(SERIALIZED_NAME_SUBTOTAL)
  @javax.annotation.Nullable
  private String subtotal;

  public OrderRefundLineItemsInnerTaxesInner() {
  }

  public OrderRefundLineItemsInnerTaxesInner id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Tax rate ID.
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public OrderRefundLineItemsInnerTaxesInner total(@javax.annotation.Nullable String total) {
    this.total = total;
    return this;
  }

  /**
   * Tax total.
   * @return total
   */
  @javax.annotation.Nullable
  public String getTotal() {
    return total;
  }

  public void setTotal(@javax.annotation.Nullable String total) {
    this.total = total;
  }


  public OrderRefundLineItemsInnerTaxesInner subtotal(@javax.annotation.Nullable String subtotal) {
    this.subtotal = subtotal;
    return this;
  }

  /**
   * Tax subtotal.
   * @return subtotal
   */
  @javax.annotation.Nullable
  public String getSubtotal() {
    return subtotal;
  }

  public void setSubtotal(@javax.annotation.Nullable String subtotal) {
    this.subtotal = subtotal;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderRefundLineItemsInnerTaxesInner orderRefundLineItemsInnerTaxesInner = (OrderRefundLineItemsInnerTaxesInner) o;
    return Objects.equals(this.id, orderRefundLineItemsInnerTaxesInner.id) &&
        Objects.equals(this.total, orderRefundLineItemsInnerTaxesInner.total) &&
        Objects.equals(this.subtotal, orderRefundLineItemsInnerTaxesInner.subtotal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, total, subtotal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderRefundLineItemsInnerTaxesInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    subtotal: ").append(toIndentedString(subtotal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("total");
    openapiFields.add("subtotal");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OrderRefundLineItemsInnerTaxesInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrderRefundLineItemsInnerTaxesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrderRefundLineItemsInnerTaxesInner is not found in the empty JSON string", OrderRefundLineItemsInnerTaxesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OrderRefundLineItemsInnerTaxesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OrderRefundLineItemsInnerTaxesInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("total") != null && !jsonObj.get("total").isJsonNull()) && !jsonObj.get("total").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `total` to be a primitive type in the JSON string but got `%s`", jsonObj.get("total").toString()));
      }
      if ((jsonObj.get("subtotal") != null && !jsonObj.get("subtotal").isJsonNull()) && !jsonObj.get("subtotal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subtotal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subtotal").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrderRefundLineItemsInnerTaxesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrderRefundLineItemsInnerTaxesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrderRefundLineItemsInnerTaxesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrderRefundLineItemsInnerTaxesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<OrderRefundLineItemsInnerTaxesInner>() {
           @Override
           public void write(JsonWriter out, OrderRefundLineItemsInnerTaxesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrderRefundLineItemsInnerTaxesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OrderRefundLineItemsInnerTaxesInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OrderRefundLineItemsInnerTaxesInner
   * @throws IOException if the JSON string is invalid with respect to OrderRefundLineItemsInnerTaxesInner
   */
  public static OrderRefundLineItemsInnerTaxesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrderRefundLineItemsInnerTaxesInner.class);
  }

  /**
   * Convert an instance of OrderRefundLineItemsInnerTaxesInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

