/*
 * WooCommerce REST API
 * The REST API is a powerful part of WooCommerce which lets you read and write various parts of WooCommerce data such as orders, products, coupons, customers, and shipping zones.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.woocommerce.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.woocommerce.api.client.invoker.JSON;

/**
 * PaymentGateway
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class PaymentGateway {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  @javax.annotation.Nullable
  private Integer order;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String SERIALIZED_NAME_METHOD_TITLE = "method_title";
  @SerializedName(SERIALIZED_NAME_METHOD_TITLE)
  @javax.annotation.Nullable
  private String methodTitle;

  public static final String SERIALIZED_NAME_METHOD_DESCRIPTION = "method_description";
  @SerializedName(SERIALIZED_NAME_METHOD_DESCRIPTION)
  @javax.annotation.Nullable
  private String methodDescription;

  public static final String SERIALIZED_NAME_METHOD_SUPPORTS = "method_supports";
  @SerializedName(SERIALIZED_NAME_METHOD_SUPPORTS)
  @javax.annotation.Nullable
  private List<String> methodSupports = new ArrayList<>();

  public static final String SERIALIZED_NAME_SETTINGS = "settings";
  @SerializedName(SERIALIZED_NAME_SETTINGS)
  @javax.annotation.Nullable
  private Object settings;

  public PaymentGateway() {
  }

  public PaymentGateway id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Payment gateway ID. read-only
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public PaymentGateway title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Payment gateway title on checkout.
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public PaymentGateway description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Payment gateway description on checkout.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public PaymentGateway order(@javax.annotation.Nullable Integer order) {
    this.order = order;
    return this;
  }

  /**
   * Payment gateway sort order.
   * @return order
   */
  @javax.annotation.Nullable
  public Integer getOrder() {
    return order;
  }

  public void setOrder(@javax.annotation.Nullable Integer order) {
    this.order = order;
  }


  public PaymentGateway enabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Payment gateway enabled status.
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public PaymentGateway methodTitle(@javax.annotation.Nullable String methodTitle) {
    this.methodTitle = methodTitle;
    return this;
  }

  /**
   * Payment gateway method title. read-only
   * @return methodTitle
   */
  @javax.annotation.Nullable
  public String getMethodTitle() {
    return methodTitle;
  }

  public void setMethodTitle(@javax.annotation.Nullable String methodTitle) {
    this.methodTitle = methodTitle;
  }


  public PaymentGateway methodDescription(@javax.annotation.Nullable String methodDescription) {
    this.methodDescription = methodDescription;
    return this;
  }

  /**
   * Payment gateway method description. read-only
   * @return methodDescription
   */
  @javax.annotation.Nullable
  public String getMethodDescription() {
    return methodDescription;
  }

  public void setMethodDescription(@javax.annotation.Nullable String methodDescription) {
    this.methodDescription = methodDescription;
  }


  public PaymentGateway methodSupports(@javax.annotation.Nullable List<String> methodSupports) {
    this.methodSupports = methodSupports;
    return this;
  }

  public PaymentGateway addMethodSupportsItem(String methodSupportsItem) {
    if (this.methodSupports == null) {
      this.methodSupports = new ArrayList<>();
    }
    this.methodSupports.add(methodSupportsItem);
    return this;
  }

  /**
   * Supported features for this payment gateway. read-only
   * @return methodSupports
   */
  @javax.annotation.Nullable
  public List<String> getMethodSupports() {
    return methodSupports;
  }

  public void setMethodSupports(@javax.annotation.Nullable List<String> methodSupports) {
    this.methodSupports = methodSupports;
  }


  public PaymentGateway settings(@javax.annotation.Nullable Object settings) {
    this.settings = settings;
    return this;
  }

  /**
   * Payment gateway settings.
   * @return settings
   */
  @javax.annotation.Nullable
  public Object getSettings() {
    return settings;
  }

  public void setSettings(@javax.annotation.Nullable Object settings) {
    this.settings = settings;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentGateway paymentGateway = (PaymentGateway) o;
    return Objects.equals(this.id, paymentGateway.id) &&
        Objects.equals(this.title, paymentGateway.title) &&
        Objects.equals(this.description, paymentGateway.description) &&
        Objects.equals(this.order, paymentGateway.order) &&
        Objects.equals(this.enabled, paymentGateway.enabled) &&
        Objects.equals(this.methodTitle, paymentGateway.methodTitle) &&
        Objects.equals(this.methodDescription, paymentGateway.methodDescription) &&
        Objects.equals(this.methodSupports, paymentGateway.methodSupports) &&
        Objects.equals(this.settings, paymentGateway.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, description, order, enabled, methodTitle, methodDescription, methodSupports, settings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentGateway {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    methodTitle: ").append(toIndentedString(methodTitle)).append("\n");
    sb.append("    methodDescription: ").append(toIndentedString(methodDescription)).append("\n");
    sb.append("    methodSupports: ").append(toIndentedString(methodSupports)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("title");
    openapiFields.add("description");
    openapiFields.add("order");
    openapiFields.add("enabled");
    openapiFields.add("method_title");
    openapiFields.add("method_description");
    openapiFields.add("method_supports");
    openapiFields.add("settings");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PaymentGateway
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PaymentGateway.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentGateway is not found in the empty JSON string", PaymentGateway.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PaymentGateway.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PaymentGateway` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("method_title") != null && !jsonObj.get("method_title").isJsonNull()) && !jsonObj.get("method_title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `method_title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method_title").toString()));
      }
      if ((jsonObj.get("method_description") != null && !jsonObj.get("method_description").isJsonNull()) && !jsonObj.get("method_description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `method_description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method_description").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("method_supports") != null && !jsonObj.get("method_supports").isJsonNull() && !jsonObj.get("method_supports").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `method_supports` to be an array in the JSON string but got `%s`", jsonObj.get("method_supports").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentGateway.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentGateway' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentGateway> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentGateway.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentGateway>() {
           @Override
           public void write(JsonWriter out, PaymentGateway value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentGateway read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PaymentGateway given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PaymentGateway
   * @throws IOException if the JSON string is invalid with respect to PaymentGateway
   */
  public static PaymentGateway fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentGateway.class);
  }

  /**
   * Convert an instance of PaymentGateway to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

