/*
 * WooCommerce REST API
 * The REST API is a powerful part of WooCommerce which lets you read and write various parts of WooCommerce data such as orders, products, coupons, customers, and shipping zones.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.woocommerce.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import pl.wtx.woocommerce.api.client.model.ReportListItemLinksSelfInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.woocommerce.api.client.invoker.JSON;

/**
 * List of links.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ShippingZoneLinks {
  public static final String SERIALIZED_NAME_SELF = "self";
  @SerializedName(SERIALIZED_NAME_SELF)
  @javax.annotation.Nullable
  private List<ReportListItemLinksSelfInner> self = new ArrayList<>();

  public static final String SERIALIZED_NAME_COLLECTION = "collection";
  @SerializedName(SERIALIZED_NAME_COLLECTION)
  @javax.annotation.Nullable
  private List<ReportListItemLinksSelfInner> collection = new ArrayList<>();

  public ShippingZoneLinks() {
  }

  public ShippingZoneLinks self(@javax.annotation.Nullable List<ReportListItemLinksSelfInner> self) {
    this.self = self;
    return this;
  }

  public ShippingZoneLinks addSelfItem(ReportListItemLinksSelfInner selfItem) {
    if (this.self == null) {
      this.self = new ArrayList<>();
    }
    this.self.add(selfItem);
    return this;
  }

  /**
   * Get self
   * @return self
   */
  @javax.annotation.Nullable
  public List<ReportListItemLinksSelfInner> getSelf() {
    return self;
  }

  public void setSelf(@javax.annotation.Nullable List<ReportListItemLinksSelfInner> self) {
    this.self = self;
  }


  public ShippingZoneLinks collection(@javax.annotation.Nullable List<ReportListItemLinksSelfInner> collection) {
    this.collection = collection;
    return this;
  }

  public ShippingZoneLinks addCollectionItem(ReportListItemLinksSelfInner collectionItem) {
    if (this.collection == null) {
      this.collection = new ArrayList<>();
    }
    this.collection.add(collectionItem);
    return this;
  }

  /**
   * Get collection
   * @return collection
   */
  @javax.annotation.Nullable
  public List<ReportListItemLinksSelfInner> getCollection() {
    return collection;
  }

  public void setCollection(@javax.annotation.Nullable List<ReportListItemLinksSelfInner> collection) {
    this.collection = collection;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShippingZoneLinks shippingZoneLinks = (ShippingZoneLinks) o;
    return Objects.equals(this.self, shippingZoneLinks.self) &&
        Objects.equals(this.collection, shippingZoneLinks.collection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, collection);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShippingZoneLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    collection: ").append(toIndentedString(collection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("self");
    openapiFields.add("collection");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ShippingZoneLinks
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ShippingZoneLinks.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ShippingZoneLinks is not found in the empty JSON string", ShippingZoneLinks.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ShippingZoneLinks.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ShippingZoneLinks` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("self") != null && !jsonObj.get("self").isJsonNull()) {
        JsonArray jsonArrayself = jsonObj.getAsJsonArray("self");
        if (jsonArrayself != null) {
          // ensure the json data is an array
          if (!jsonObj.get("self").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `self` to be an array in the JSON string but got `%s`", jsonObj.get("self").toString()));
          }

          // validate the optional field `self` (array)
          for (int i = 0; i < jsonArrayself.size(); i++) {
            ReportListItemLinksSelfInner.validateJsonElement(jsonArrayself.get(i));
          };
        }
      }
      if (jsonObj.get("collection") != null && !jsonObj.get("collection").isJsonNull()) {
        JsonArray jsonArraycollection = jsonObj.getAsJsonArray("collection");
        if (jsonArraycollection != null) {
          // ensure the json data is an array
          if (!jsonObj.get("collection").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `collection` to be an array in the JSON string but got `%s`", jsonObj.get("collection").toString()));
          }

          // validate the optional field `collection` (array)
          for (int i = 0; i < jsonArraycollection.size(); i++) {
            ReportListItemLinksSelfInner.validateJsonElement(jsonArraycollection.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ShippingZoneLinks.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ShippingZoneLinks' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ShippingZoneLinks> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ShippingZoneLinks.class));

       return (TypeAdapter<T>) new TypeAdapter<ShippingZoneLinks>() {
           @Override
           public void write(JsonWriter out, ShippingZoneLinks value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ShippingZoneLinks read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ShippingZoneLinks given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ShippingZoneLinks
   * @throws IOException if the JSON string is invalid with respect to ShippingZoneLinks
   */
  public static ShippingZoneLinks fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ShippingZoneLinks.class);
  }

  /**
   * Convert an instance of ShippingZoneLinks to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

